### ISSUE TITLE
Can you please help me out with this?

### ISSUE THREAD

**Issue by abhinavg916** [jhnwr/scrapeamazon#1]
I am getting this error. 
```
Traceback (most recent call last):
  File "c:\Users\Abhin\Desktop\web-scrapping\amazon_scapper.py", line 28, in <module>
    tvprices.append(getPrice(url))
  File "c:\Users\Abhin\Desktop\web-scrapping\amazon_scapper.py", line 11, in getPrice
    r.html.render(sleep=1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests_html.py", line 598, in render
    content, result, page = self.session.loop.run_until_complete(self._async_render(url=self.url, script=script, sleep=sleep, wait=wait, content=self.html, reload=reload, scrolldown=scrolldown, timeout=timeout, keep_page=keep_page))
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests_html.py", line 512, in _async_render
    await page.goto(url, options={'timeout': int(timeout * 1000)})
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyppeteer\page.py", line 885, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 8000 ms exceeded.
```

**Comment by abhinavg916** [comment]
I got this, it was due to my internet connection speed.

The default timeout for r.html.render() is 8 seconds. You get this error if all the JavaScript codes are not loaded within 8 seconds. You can fix this by changing the default timeout, let's say 20 seconds. Use the following code for the future:
set timeout=20,30,etc.
Solution:
```
r.html.render(timeout=20)
```

Thanks for the tutorial! 💯
